function save_dir_doc(data,mdl,I,lik)

orientation_direction_bayes = struct( ...
    'noise_model',struct('type',{'proportional'},'offset',[],'slope',[]), ...
    'other_parameters',struct('independent_variable',{},'independent_variable_value',[]), ...
    'marginal_likelihood',struct( ...
        'theta_pref',struct('values',[],'likelihoods',[]), ...
        'Rp',struct('values',[],'likelihoods',[]), ...
        'Rn',struct('values',[],'likelihoods',[]), ...
        'sigma',struct('values',[],'likelihoods',[]), ...
        'Rsp',struct('values',[],'likelihoods',[])), ...
    'maximum_likelihood_parameters',struct('theta_pref',[],'Rp',[],'Rn',[],'sigma',[],'Rsp',[]), ...
    'descriptors',struct( ...
        'di',struct('values',[],'likelihoods',[]), ...
        'oi',struct('values',[],'likelihoods',[]), ...
        'cv',struct('values',[],'likelihoods',[]), ...
        'dir_cv',struct('values',[],'likelihoods',[])));
orientation_direction_bayes = orientation_direction_bayes([]);

orientation_direction_bayes(end+1).noise_model.offset = mdl.Coefficients{1,1};
orientation_direction_bayes(end).noise_model.slope = mdl.Coefficients{2,1};

orientation_direction_bayes(end).other_parameters.independent_variable = data.document_properties.stimulus_tuningcurve.independent_variable_label;
orientation_direction_bayes(end).other_parameters.independent_variable_value = data.document_properties.stimulus_tuningcurve.independent_variable_value;

orientation_direction_bayes(end).marginal_likelihood.theta_pref.values = I.Op;
orientation_direction_bayes(end).marginal_likelihood.theta_pref.likelihoods = lik.Op;
orientation_direction_bayes(end).marginal_likelihood.Rp.values = I.Rp;
orientation_direction_bayes(end).marginal_likelihood.Rp.likelihoods = lik.Rp;
orientation_direction_bayes(end).marginal_likelihood.Rn.values = [];%I.Alpha need to be transformed to value of Rn
orientation_direction_bayes(end).marginal_likelihood.Rn.likelihoods = [];%lik.Alpha;
orientation_direction_bayes(end).marginal_likelihood.sigma.values = I.Sig;
orientation_direction_bayes(end).marginal_likelihood.sigma.likelihoods = lik.Sig;
orientation_direction_bayes(end).marginal_likelihood.Rsp.values = data.document_properties.stimulus_tuningcurve.response_mean;%data
orientation_direction_bayes(end).marginal_likelihood.Rsp.likelihoods = lik.vrsp;%it have 360 angles

orientation_direction_bayes(end).maximum_likelihood_parameters = lik.maximum_likelihood_parameters;

save orientation_direction_bayes orientation_direction_bayes;
end